### ISSUE TITLE
java-tool.jar does not extract constructors

### ISSUE THREAD

**Issue by shao-hua-li** [basedrhys/obfuscated-code2vec#10]
Hi,

I found that the `java-tool.jar` ignored all constructor methods. For example, for the following java file, java-tool.jar only returns the `public int hello() {return 1;}`.

```
class Hello {
    public Hello() {
        
    }
    public int hello() {
        return 1;
    }
}
```

**Comment by shao-hua-li** [comment]
I figure it out by my own.

Just a hint for anyone else wants to do the same thing: add `allFunc.addAll(obfuscated.getConstructors());` to line 111 to `/src/main/java/SpoonRunner/FileObfuscator.java`.

**Comment by basedrhys** [comment]
Hi,

Glad you figured it out. Just a note - `java-tool.jar` was created specifically for this project and for use with the code2vec method embedder. If you pass a constructor to code2vec it throws an exception as there is no method name to predict; they were left out of `java-tool.jar` for that same reason.
